dist: trusty

group: edge

language: java

sudo: required

jdk: openjdk8

cache:
  directories:
    - $HOME/.m2
script:
  - cd icecream-shop-manager
  - mvn clean install

after_success:
  - mvn clean test jacoco:report coveralls:report -DTOS_ASSIGN2_CVRLS_TOKEN=$TOS_ASSIGN2_CVRLS_TOKEN
